# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 497e5e8e0095e13ebc20be140c275abc7584fc0c3414dd9c27f40fa6364a1a569937e3a8fa913e43d96875a69b6edd7f11f0f8db84c590d29b5186c66fa184cc

test:
  secret_key_base: 15fd2809d303c5abacd4c7af00df1fe505105d2dcb38b0b8798864a7c6e2387a6cbc8260aeca4b1d607ce973a14f824579696ebe2e0f064be180f8e536ae11df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
